### ISSUE TITLE
Image not showing up 

### ISSUE THREAD

**Issue by polo0016** [polo0016/mtm6201-week1#1]
Hi Prof @abhaysharma,

I was making sure that my page had all the requirements, but I'm noticing that my image doesn't show on my page, but it does show on the live server. I tried with a different picture and renaming the folder. No success. 

https://polo0016.github.io/mtm6201-week1/

Could you please help me figure out what is wrong? Thank you!

<img width="1125" alt="Screen Shot 2022-05-12 at 5 42 11 PM" src="https://user-images.githubusercontent.com/97468716/168173113-da18d211-d95f-4bad-af11-fef3dd2072e8.png">

**Comment by abhaysharma** [comment]
@polo0016 the issue is with the image path you will need to remove / from the start of the src. On GitHub if you start a path with a / it means you want to start the path from your main account which moves you out of the repository you are in.

**Comment by polo0016** [comment]
Thank you!
